:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2012.4
:: Copyright (C) 2012 Xilinx Inc. All rights reserved.
:: 
:: ==============================================================


@echo off

vivado -notrace -mode batch -source run_ippack.tcl
