// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.4
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrix_mul_thread (
        ap_clk,
        ap_rst,
        ReadEnablePort_0,
        ReadEnablePort_0_ap_vld,
        ReadEmptyPort_0,
        ReadDataPort_0,
        WriteEnablePort_0,
        WriteEnablePort_0_ap_vld,
        WriteFullPort_0,
        WriteDataPort_0,
        WriteDataPort_0_ap_vld,
        m_result_address0,
        m_result_ce0,
        m_result_we0,
        m_result_d0,
        m_result_q0,
        m_operand1_address0,
        m_operand1_ce0,
        m_operand1_we0,
        m_operand1_d0,
        m_operand1_q0,
        m_operand2_address0,
        m_operand2_ce0,
        m_operand2_we0,
        m_operand2_d0,
        m_operand2_q0
);

input   ap_clk;
input   ap_rst;
output  [0:0] ReadEnablePort_0;
output   ReadEnablePort_0_ap_vld;
input  [0:0] ReadEmptyPort_0;
input  [31:0] ReadDataPort_0;
output  [0:0] WriteEnablePort_0;
output   WriteEnablePort_0_ap_vld;
input  [0:0] WriteFullPort_0;
output  [31:0] WriteDataPort_0;
output   WriteDataPort_0_ap_vld;
output  [16:0] m_result_address0;
output   m_result_ce0;
output   m_result_we0;
output  [31:0] m_result_d0;
input  [31:0] m_result_q0;
output  [16:0] m_operand1_address0;
output   m_operand1_ce0;
output   m_operand1_we0;
output  [31:0] m_operand1_d0;
input  [31:0] m_operand1_q0;
output  [16:0] m_operand2_address0;
output   m_operand2_ce0;
output   m_operand2_we0;
output  [31:0] m_operand2_d0;
input  [31:0] m_operand2_q0;

reg[0:0] ReadEnablePort_0;
reg ReadEnablePort_0_ap_vld;
reg[0:0] WriteEnablePort_0;
reg WriteEnablePort_0_ap_vld;
reg[31:0] WriteDataPort_0;
reg WriteDataPort_0_ap_vld;
reg[16:0] m_result_address0;
reg m_result_ce0;
reg m_result_we0;
reg[16:0] m_operand1_address0;
reg m_operand1_ce0;
reg m_operand1_we0;
reg[16:0] m_operand2_address0;
reg m_operand2_ce0;
reg m_operand2_we0;
reg   [16:0] m_operand1_addr_1_reg_557;
reg   [4:0] ap_CS_fsm = 5'b00001;
wire   [16:0] i_3_fu_373_p2;
reg   [16:0] i_3_reg_565;
wire   [16:0] ptData32_assign_4_rec_fu_389_p2;
reg   [16:0] ptData32_assign_4_rec_reg_573;
wire   [0:0] grp_wireread_fu_140_p2;
reg   [16:0] m_operand2_addr_1_reg_578;
wire   [16:0] i_5_fu_406_p2;
reg   [16:0] i_5_reg_586;
wire   [16:0] ptData32_assign_7_rec_fu_422_p2;
reg   [16:0] ptData32_assign_7_rec_reg_594;
wire   [16:0] next_mul1_fu_428_p2;
reg   [16:0] next_mul1_reg_599;
wire   [8:0] i_6_fu_440_p2;
reg   [8:0] i_6_reg_607;
wire   [16:0] j_cast_fu_446_p1;
reg   [16:0] j_cast_reg_612;
wire   [8:0] j_1_fu_456_p2;
reg   [8:0] j_1_reg_621;
wire   [8:0] k_1_fu_472_p2;
reg   [8:0] k_1_reg_629;
wire   [0:0] exitcond8_fu_466_p2;
wire   [16:0] next_mul_fu_489_p2;
reg   [16:0] next_mul_reg_639;
reg   [31:0] m_operand1_load_reg_649;
reg   [31:0] m_operand2_load_reg_654;
wire   [31:0] grp_fu_515_p2;
reg   [31:0] tmp_6_reg_659;
wire   [31:0] sum_1_fu_519_p2;
reg   [16:0] m_result_addr_1_reg_669;
wire   [16:0] i_7_fu_535_p2;
reg   [16:0] i_7_reg_677;
wire   [16:0] ptData32_assign_8_rec_fu_551_p2;
reg   [16:0] ptData32_assign_8_rec_reg_685;
wire   [0:0] grp_wireread_fu_153_p2;
reg   [16:0] ptData32_assign_1_rec_reg_220;
reg   [16:0] i_reg_232;
reg   [16:0] ptData32_assign_3_rec_reg_244;
wire   [0:0] exitcond_fu_367_p2;
reg   [16:0] i_1_reg_256;
reg   [8:0] i_2_reg_268;
wire   [0:0] exitcond9_fu_450_p2;
wire   [0:0] exitcond1_fu_400_p2;
reg   [16:0] phi_mul1_reg_279;
reg   [8:0] j_reg_291;
wire   [0:0] exitcond2_fu_434_p2;
reg   [8:0] k_reg_302;
reg   [31:0] sum_reg_313;
reg   [16:0] phi_mul_reg_326;
reg   [16:0] ptData32_assign_6_rec_reg_337;
reg   [16:0] i_4_reg_349;
wire   [31:0] ptData32_assign_1_rec_cast_fu_362_p1;
wire   [31:0] ptData32_assign_3_rec_cast_fu_395_p1;
wire   [31:0] tmp_2_cast_fu_484_p1;
wire   [31:0] tmp_5_cast_fu_500_p1;
wire   [31:0] tmp_1_cast_fu_510_p1;
wire   [31:0] ptData32_assign_6_rec_cast_fu_524_p1;
wire   [0:0] tmp_3_fu_379_p2;
wire   [16:0] ptData3_0_i_cast_fu_385_p1;
wire   [0:0] tmp_8_fu_412_p2;
wire   [16:0] ptData3_0_i1_cast_fu_418_p1;
wire   [16:0] k_cast_fu_462_p1;
wire   [16:0] tmp_2_fu_478_p2;
wire   [16:0] tmp_5_fu_495_p2;
wire   [16:0] tmp_1_fu_505_p2;
wire   [31:0] grp_fu_515_p0;
wire   [31:0] grp_fu_515_p1;
wire   [0:0] tmp_s_fu_541_p2;
wire   [16:0] ptData3_0_i2_cast_fu_547_p1;
wire    grp_fu_515_ce;
wire   [0:0] exitcond7_fu_529_p2;
reg   [4:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st2_fsm_1 = 5'b00001;
parameter    ap_ST_st3_fsm_2 = 5'b00010;
parameter    ap_ST_st4_fsm_3 = 5'b00011;
parameter    ap_ST_st5_fsm_4 = 5'b00100;
parameter    ap_ST_st6_fsm_5 = 5'b00101;
parameter    ap_ST_st7_fsm_6 = 5'b00110;
parameter    ap_ST_st8_fsm_7 = 5'b00111;
parameter    ap_ST_st9_fsm_8 = 5'b01000;
parameter    ap_ST_st10_fsm_9 = 5'b01001;
parameter    ap_ST_st11_fsm_10 = 5'b01010;
parameter    ap_ST_st12_fsm_11 = 5'b01011;
parameter    ap_ST_st13_fsm_12 = 5'b01100;
parameter    ap_ST_st14_fsm_13 = 5'b01101;
parameter    ap_ST_st15_fsm_14 = 5'b01110;
parameter    ap_ST_st16_fsm_15 = 5'b01111;
parameter    ap_ST_st17_fsm_16 = 5'b10000;
parameter    ap_ST_st18_fsm_17 = 5'b10001;
parameter    ap_ST_st19_fsm_18 = 5'b10010;
parameter    ap_ST_st20_fsm_19 = 5'b10011;
parameter    ap_ST_st21_fsm_20 = 5'b10100;
parameter    ap_ST_st22_fsm_21 = 5'b10101;
parameter    ap_ST_st23_fsm_22 = 5'b10110;
parameter    ap_ST_st24_fsm_23 = 5'b10111;
parameter    ap_ST_st25_fsm_24 = 5'b11000;
parameter    ap_ST_st26_fsm_25 = 5'b11001;
parameter    ap_ST_st27_fsm_26 = 5'b11010;
parameter    ap_ST_st28_fsm_27 = 5'b11011;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv17_0 = 17'b00000000000000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv17_15F90 = 17'b10101111110010000;
parameter    ap_const_lv17_1 = 17'b00000000000000001;
parameter    ap_const_lv17_15F8F = 17'b10101111110001111;
parameter    ap_const_lv17_12C = 17'b00000000100101100;
parameter    ap_const_lv9_12C = 9'b100101100;
parameter    ap_const_lv9_1 = 9'b000000001;
parameter    ap_true = 1'b1;


matrix_mul_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matrix_mul_mul_32s_32s_32_6_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_515_p0 ),
    .din1( grp_fu_515_p1 ),
    .ce( grp_fu_515_ce ),
    .dout( grp_fu_515_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st2_fsm_1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        i_1_reg_256 <= i_5_reg_586;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_367_p2))) begin
        i_1_reg_256 <= ap_const_lv17_0;
    end
    if (((ap_ST_st9_fsm_8 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_400_p2))) begin
        i_2_reg_268 <= ap_const_lv9_0;
    end else if (((ap_ST_st14_fsm_13 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond9_fu_450_p2))) begin
        i_2_reg_268 <= i_6_reg_607;
    end
    if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        i_3_reg_565 <= i_3_fu_373_p2;
    end
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        i_4_reg_349 <= i_7_reg_677;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_434_p2))) begin
        i_4_reg_349 <= ap_const_lv17_0;
    end
    if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        i_5_reg_586 <= i_5_fu_406_p2;
    end
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        i_6_reg_607 <= i_6_fu_440_p2;
    end
    if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        i_7_reg_677 <= i_7_fu_535_p2;
    end
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        i_reg_232 <= i_3_reg_565;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        i_reg_232 <= ap_const_lv17_0;
    end
    if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        j_1_reg_621 <= j_1_fu_456_p2;
    end
    if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        j_cast_reg_612[0] <= j_cast_fu_446_p1[0];
        j_cast_reg_612[1] <= j_cast_fu_446_p1[1];
        j_cast_reg_612[2] <= j_cast_fu_446_p1[2];
        j_cast_reg_612[3] <= j_cast_fu_446_p1[3];
        j_cast_reg_612[4] <= j_cast_fu_446_p1[4];
        j_cast_reg_612[5] <= j_cast_fu_446_p1[5];
        j_cast_reg_612[6] <= j_cast_fu_446_p1[6];
        j_cast_reg_612[7] <= j_cast_fu_446_p1[7];
        j_cast_reg_612[8] <= j_cast_fu_446_p1[8];
    end
    if (((ap_ST_st13_fsm_12 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_434_p2))) begin
        j_reg_291 <= ap_const_lv9_0;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond8_fu_466_p2))) begin
        j_reg_291 <= j_1_reg_621;
    end
    if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        k_1_reg_629 <= k_1_fu_472_p2;
    end
    if (((ap_ST_st14_fsm_13 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_450_p2))) begin
        k_reg_302 <= ap_const_lv9_0;
    end else if ((ap_ST_st23_fsm_22 == ap_CS_fsm)) begin
        k_reg_302 <= k_1_reg_629;
    end
    if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        m_operand1_addr_1_reg_557 <= ptData32_assign_1_rec_cast_fu_362_p1;
    end
    if ((ap_ST_st16_fsm_15 == ap_CS_fsm)) begin
        m_operand1_load_reg_649 <= m_operand1_q0;
    end
    if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        m_operand2_addr_1_reg_578 <= ptData32_assign_3_rec_cast_fu_395_p1;
    end
    if ((ap_ST_st16_fsm_15 == ap_CS_fsm)) begin
        m_operand2_load_reg_654 <= m_operand2_q0;
    end
    if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        m_result_addr_1_reg_669 <= ptData32_assign_6_rec_cast_fu_524_p1;
    end
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        next_mul1_reg_599 <= next_mul1_fu_428_p2;
    end
    if (((ap_ST_st15_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_466_p2))) begin
        next_mul_reg_639 <= next_mul_fu_489_p2;
    end
    if (((ap_ST_st9_fsm_8 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_400_p2))) begin
        phi_mul1_reg_279 <= ap_const_lv17_0;
    end else if (((ap_ST_st14_fsm_13 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond9_fu_450_p2))) begin
        phi_mul1_reg_279 <= next_mul1_reg_599;
    end
    if (((ap_ST_st14_fsm_13 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_450_p2))) begin
        phi_mul_reg_326 <= ap_const_lv17_0;
    end else if ((ap_ST_st23_fsm_22 == ap_CS_fsm)) begin
        phi_mul_reg_326 <= next_mul_reg_639;
    end
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        ptData32_assign_1_rec_reg_220 <= ptData32_assign_4_rec_reg_573;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        ptData32_assign_1_rec_reg_220 <= ap_const_lv17_0;
    end
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        ptData32_assign_3_rec_reg_244 <= ptData32_assign_7_rec_reg_594;
    end else if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_367_p2))) begin
        ptData32_assign_3_rec_reg_244 <= ap_const_lv17_0;
    end
    if (((ap_ST_st6_fsm_5 == ap_CS_fsm) & (grp_wireread_fu_140_p2 == ap_const_lv1_0))) begin
        ptData32_assign_4_rec_reg_573 <= ptData32_assign_4_rec_fu_389_p2;
    end
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        ptData32_assign_6_rec_reg_337 <= ptData32_assign_8_rec_reg_685;
    end else if (((ap_ST_st13_fsm_12 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_434_p2))) begin
        ptData32_assign_6_rec_reg_337 <= ap_const_lv17_0;
    end
    if (((grp_wireread_fu_140_p2 == ap_const_lv1_0) & (ap_ST_st10_fsm_9 == ap_CS_fsm))) begin
        ptData32_assign_7_rec_reg_594 <= ptData32_assign_7_rec_fu_422_p2;
    end
    if (((ap_ST_st25_fsm_24 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_153_p2))) begin
        ptData32_assign_8_rec_reg_685 <= ptData32_assign_8_rec_fu_551_p2;
    end
    if (((ap_ST_st14_fsm_13 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_450_p2))) begin
        sum_reg_313 <= ap_const_lv32_0;
    end else if ((ap_ST_st23_fsm_22 == ap_CS_fsm)) begin
        sum_reg_313 <= sum_1_fu_519_p2;
    end
    if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        tmp_6_reg_659 <= grp_fu_515_p2;
    end
end

/// ReadEnablePort_0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_140_p2)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        ReadEnablePort_0 = ap_const_lv1_0;
    end else if ((((ap_ST_st6_fsm_5 == ap_CS_fsm) & (grp_wireread_fu_140_p2 == ap_const_lv1_0)) | ((grp_wireread_fu_140_p2 == ap_const_lv1_0) & (ap_ST_st10_fsm_9 == ap_CS_fsm)))) begin
        ReadEnablePort_0 = ap_const_lv1_1;
    end else begin
        ReadEnablePort_0 = ap_const_lv1_1;
    end
end

/// ReadEnablePort_0_ap_vld assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_140_p2)
begin
    if ((((ap_ST_st6_fsm_5 == ap_CS_fsm) & (grp_wireread_fu_140_p2 == ap_const_lv1_0)) | ((grp_wireread_fu_140_p2 == ap_const_lv1_0) & (ap_ST_st10_fsm_9 == ap_CS_fsm)) | (ap_ST_st7_fsm_6 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        ReadEnablePort_0_ap_vld = ap_const_logic_1;
    end else begin
        ReadEnablePort_0_ap_vld = ap_const_logic_0;
    end
end

/// WriteDataPort_0 assign process. ///
always @ (m_result_q0 or ap_CS_fsm)
begin
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        WriteDataPort_0 = ap_const_lv32_0;
    end else if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        WriteDataPort_0 = m_result_q0;
    end else begin
        WriteDataPort_0 = ap_const_lv32_0;
    end
end

/// WriteDataPort_0_ap_vld assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st26_fsm_25 == ap_CS_fsm) | (ap_ST_st27_fsm_26 == ap_CS_fsm))) begin
        WriteDataPort_0_ap_vld = ap_const_logic_1;
    end else begin
        WriteDataPort_0_ap_vld = ap_const_logic_0;
    end
end

/// WriteEnablePort_0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        WriteEnablePort_0 = ap_const_lv1_0;
    end else if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        WriteEnablePort_0 = ap_const_lv1_1;
    end else begin
        WriteEnablePort_0 = ap_const_lv1_1;
    end
end

/// WriteEnablePort_0_ap_vld assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st26_fsm_25 == ap_CS_fsm) | (ap_ST_st27_fsm_26 == ap_CS_fsm))) begin
        WriteEnablePort_0_ap_vld = ap_const_logic_1;
    end else begin
        WriteEnablePort_0_ap_vld = ap_const_logic_0;
    end
end

/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or grp_wireread_fu_140_p2 or exitcond8_fu_466_p2 or grp_wireread_fu_153_p2 or exitcond_fu_367_p2 or exitcond9_fu_450_p2 or exitcond1_fu_400_p2 or exitcond2_fu_434_p2 or exitcond7_fu_529_p2)
begin
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st28_fsm_27;
    end else if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st27_fsm_26;
    end else if (((ap_ST_st25_fsm_24 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_153_p2))) begin
        ap_NS_fsm = ap_ST_st26_fsm_25;
    end else if ((((ap_ST_st24_fsm_23 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_529_p2)) | ((ap_ST_st25_fsm_24 == ap_CS_fsm) & ~(ap_const_lv1_0 == grp_wireread_fu_153_p2)))) begin
        ap_NS_fsm = ap_ST_st25_fsm_24;
    end else if ((ap_ST_st22_fsm_21 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st23_fsm_22;
    end else if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st22_fsm_21;
    end else if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st21_fsm_20;
    end else if ((ap_ST_st19_fsm_18 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st20_fsm_19;
    end else if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st19_fsm_18;
    end else if ((ap_ST_st17_fsm_16 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st18_fsm_17;
    end else if ((ap_ST_st16_fsm_15 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st17_fsm_16;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_466_p2))) begin
        ap_NS_fsm = ap_ST_st16_fsm_15;
    end else if (((ap_ST_st23_fsm_22 == ap_CS_fsm) | ((ap_ST_st14_fsm_13 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_450_p2)))) begin
        ap_NS_fsm = ap_ST_st15_fsm_14;
    end else if ((((ap_ST_st13_fsm_12 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_434_p2)) | (ap_ST_st28_fsm_27 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st24_fsm_23;
    end else if ((((ap_ST_st15_fsm_14 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond8_fu_466_p2)) | ((ap_ST_st13_fsm_12 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_434_p2)))) begin
        ap_NS_fsm = ap_ST_st14_fsm_13;
    end else if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st12_fsm_11;
    end else if (((grp_wireread_fu_140_p2 == ap_const_lv1_0) & (ap_ST_st10_fsm_9 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st11_fsm_10;
    end else if ((((ap_ST_st14_fsm_13 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond9_fu_450_p2)) | ((ap_ST_st9_fsm_8 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_400_p2)))) begin
        ap_NS_fsm = ap_ST_st13_fsm_12;
    end else if ((((ap_ST_st9_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_400_p2)) | ((ap_ST_st10_fsm_9 == ap_CS_fsm) & ~(grp_wireread_fu_140_p2 == ap_const_lv1_0)))) begin
        ap_NS_fsm = ap_ST_st10_fsm_9;
    end else if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st8_fsm_7;
    end else if (((ap_ST_st6_fsm_5 == ap_CS_fsm) & (grp_wireread_fu_140_p2 == ap_const_lv1_0))) begin
        ap_NS_fsm = ap_ST_st7_fsm_6;
    end else if ((((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_367_p2)) | (ap_ST_st12_fsm_11 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st9_fsm_8;
    end else if ((((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_367_p2)) | ((ap_ST_st6_fsm_5 == ap_CS_fsm) & ~(grp_wireread_fu_140_p2 == ap_const_lv1_0)))) begin
        ap_NS_fsm = ap_ST_st6_fsm_5;
    end else if (((ap_ST_st4_fsm_3 == ap_CS_fsm) | (ap_ST_st8_fsm_7 == ap_CS_fsm))) begin
        ap_NS_fsm = ap_ST_st5_fsm_4;
    end else if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | ((ap_ST_st24_fsm_23 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_529_p2)))) begin
        ap_NS_fsm = ap_ST_st4_fsm_3;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        ap_NS_fsm = ap_ST_st3_fsm_2;
    end else begin
        ap_NS_fsm = ap_CS_fsm;
    end
end

/// m_operand1_address0 assign process. ///
always @ (m_operand1_addr_1_reg_557 or ap_CS_fsm or grp_wireread_fu_140_p2 or exitcond8_fu_466_p2 or tmp_2_cast_fu_484_p1)
begin
    if (((ap_ST_st6_fsm_5 == ap_CS_fsm) & (grp_wireread_fu_140_p2 == ap_const_lv1_0))) begin
        m_operand1_address0 = m_operand1_addr_1_reg_557;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_466_p2))) begin
        m_operand1_address0 = tmp_2_cast_fu_484_p1;
    end else begin
        m_operand1_address0 = tmp_2_cast_fu_484_p1;
    end
end

/// m_operand1_ce0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_140_p2 or exitcond8_fu_466_p2)
begin
    if ((((ap_ST_st6_fsm_5 == ap_CS_fsm) & (grp_wireread_fu_140_p2 == ap_const_lv1_0)) | ((ap_ST_st15_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_466_p2)))) begin
        m_operand1_ce0 = ap_const_logic_1;
    end else begin
        m_operand1_ce0 = ap_const_logic_0;
    end
end

/// m_operand1_we0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_140_p2)
begin
    if (((ap_ST_st6_fsm_5 == ap_CS_fsm) & (grp_wireread_fu_140_p2 == ap_const_lv1_0))) begin
        m_operand1_we0 = ap_const_logic_1;
    end else begin
        m_operand1_we0 = ap_const_logic_0;
    end
end

/// m_operand2_address0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_140_p2 or m_operand2_addr_1_reg_578 or exitcond8_fu_466_p2 or tmp_5_cast_fu_500_p1)
begin
    if (((grp_wireread_fu_140_p2 == ap_const_lv1_0) & (ap_ST_st10_fsm_9 == ap_CS_fsm))) begin
        m_operand2_address0 = m_operand2_addr_1_reg_578;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_466_p2))) begin
        m_operand2_address0 = tmp_5_cast_fu_500_p1;
    end else begin
        m_operand2_address0 = tmp_5_cast_fu_500_p1;
    end
end

/// m_operand2_ce0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_140_p2 or exitcond8_fu_466_p2)
begin
    if ((((grp_wireread_fu_140_p2 == ap_const_lv1_0) & (ap_ST_st10_fsm_9 == ap_CS_fsm)) | ((ap_ST_st15_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond8_fu_466_p2)))) begin
        m_operand2_ce0 = ap_const_logic_1;
    end else begin
        m_operand2_ce0 = ap_const_logic_0;
    end
end

/// m_operand2_we0 assign process. ///
always @ (ap_CS_fsm or grp_wireread_fu_140_p2)
begin
    if (((grp_wireread_fu_140_p2 == ap_const_lv1_0) & (ap_ST_st10_fsm_9 == ap_CS_fsm))) begin
        m_operand2_we0 = ap_const_logic_1;
    end else begin
        m_operand2_we0 = ap_const_logic_0;
    end
end

/// m_result_address0 assign process. ///
always @ (ap_CS_fsm or exitcond8_fu_466_p2 or m_result_addr_1_reg_669 or grp_wireread_fu_153_p2 or tmp_1_cast_fu_510_p1)
begin
    if (((ap_ST_st15_fsm_14 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond8_fu_466_p2))) begin
        m_result_address0 = tmp_1_cast_fu_510_p1;
    end else if (((ap_ST_st25_fsm_24 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_153_p2))) begin
        m_result_address0 = m_result_addr_1_reg_669;
    end else begin
        m_result_address0 = tmp_1_cast_fu_510_p1;
    end
end

/// m_result_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond8_fu_466_p2 or grp_wireread_fu_153_p2)
begin
    if ((((ap_ST_st25_fsm_24 == ap_CS_fsm) & (ap_const_lv1_0 == grp_wireread_fu_153_p2)) | ((ap_ST_st15_fsm_14 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond8_fu_466_p2)))) begin
        m_result_ce0 = ap_const_logic_1;
    end else begin
        m_result_ce0 = ap_const_logic_0;
    end
end

/// m_result_we0 assign process. ///
always @ (ap_CS_fsm or exitcond8_fu_466_p2)
begin
    if (((ap_ST_st15_fsm_14 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond8_fu_466_p2))) begin
        m_result_we0 = ap_const_logic_1;
    end else begin
        m_result_we0 = ap_const_logic_0;
    end
end
assign exitcond1_fu_400_p2 = (i_1_reg_256 == ap_const_lv17_15F90? 1'b1: 1'b0);
assign exitcond2_fu_434_p2 = (i_2_reg_268 == ap_const_lv9_12C? 1'b1: 1'b0);
assign exitcond7_fu_529_p2 = (i_4_reg_349 == ap_const_lv17_15F90? 1'b1: 1'b0);
assign exitcond8_fu_466_p2 = (k_reg_302 == ap_const_lv9_12C? 1'b1: 1'b0);
assign exitcond9_fu_450_p2 = (j_reg_291 == ap_const_lv9_12C? 1'b1: 1'b0);
assign exitcond_fu_367_p2 = (i_reg_232 == ap_const_lv17_15F90? 1'b1: 1'b0);
assign grp_fu_515_ce = ap_const_logic_1;
assign grp_fu_515_p0 = m_operand2_load_reg_654;
assign grp_fu_515_p1 = m_operand1_load_reg_649;
assign grp_wireread_fu_140_p2 = ReadEmptyPort_0;
assign grp_wireread_fu_153_p2 = WriteFullPort_0;
assign i_3_fu_373_p2 = (i_reg_232 + ap_const_lv17_1);
assign i_5_fu_406_p2 = (i_1_reg_256 + ap_const_lv17_1);
assign i_6_fu_440_p2 = (i_2_reg_268 + ap_const_lv9_1);
assign i_7_fu_535_p2 = (i_4_reg_349 + ap_const_lv17_1);
assign j_1_fu_456_p2 = (j_reg_291 + ap_const_lv9_1);
assign j_cast_fu_446_p1 = $unsigned(j_reg_291);
assign k_1_fu_472_p2 = (k_reg_302 + ap_const_lv9_1);
assign k_cast_fu_462_p1 = $unsigned(k_reg_302);
assign m_operand1_d0 = ReadDataPort_0;
assign m_operand2_d0 = ReadDataPort_0;
assign m_result_d0 = sum_reg_313;
assign next_mul1_fu_428_p2 = (phi_mul1_reg_279 + ap_const_lv17_12C);
assign next_mul_fu_489_p2 = (phi_mul_reg_326 + ap_const_lv17_12C);
assign ptData32_assign_1_rec_cast_fu_362_p1 = $unsigned(ptData32_assign_1_rec_reg_220);
assign ptData32_assign_3_rec_cast_fu_395_p1 = $unsigned(ptData32_assign_3_rec_reg_244);
assign ptData32_assign_4_rec_fu_389_p2 = (ptData32_assign_1_rec_reg_220 + ptData3_0_i_cast_fu_385_p1);
assign ptData32_assign_6_rec_cast_fu_524_p1 = $unsigned(ptData32_assign_6_rec_reg_337);
assign ptData32_assign_7_rec_fu_422_p2 = (ptData32_assign_3_rec_reg_244 + ptData3_0_i1_cast_fu_418_p1);
assign ptData32_assign_8_rec_fu_551_p2 = (ptData32_assign_6_rec_reg_337 + ptData3_0_i2_cast_fu_547_p1);
assign ptData3_0_i1_cast_fu_418_p1 = $unsigned(tmp_8_fu_412_p2);
assign ptData3_0_i2_cast_fu_547_p1 = $unsigned(tmp_s_fu_541_p2);
assign ptData3_0_i_cast_fu_385_p1 = $unsigned(tmp_3_fu_379_p2);
assign sum_1_fu_519_p2 = (tmp_6_reg_659 + sum_reg_313);
assign tmp_1_cast_fu_510_p1 = $unsigned(tmp_1_fu_505_p2);
assign tmp_1_fu_505_p2 = (j_cast_reg_612 + phi_mul1_reg_279);
assign tmp_2_cast_fu_484_p1 = $unsigned(tmp_2_fu_478_p2);
assign tmp_2_fu_478_p2 = (k_cast_fu_462_p1 + phi_mul1_reg_279);
assign tmp_3_fu_379_p2 = (i_reg_232 < ap_const_lv17_15F8F? 1'b1: 1'b0);
assign tmp_5_cast_fu_500_p1 = $unsigned(tmp_5_fu_495_p2);
assign tmp_5_fu_495_p2 = (phi_mul_reg_326 + j_cast_reg_612);
assign tmp_8_fu_412_p2 = (i_1_reg_256 < ap_const_lv17_15F8F? 1'b1: 1'b0);
assign tmp_s_fu_541_p2 = (i_4_reg_349 < ap_const_lv17_15F8F? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    j_cast_reg_612[16:9] <= 8'b00000000;
end



endmodule //matrix_mul_thread

