// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.4
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "matrix_mul_thread.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_mul_thread::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_mul_thread::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> matrix_mul_thread::ap_ST_st2_fsm_1 = "00001";
const sc_lv<5> matrix_mul_thread::ap_ST_st3_fsm_2 = "00010";
const sc_lv<5> matrix_mul_thread::ap_ST_st4_fsm_3 = "00011";
const sc_lv<5> matrix_mul_thread::ap_ST_st5_fsm_4 = "00100";
const sc_lv<5> matrix_mul_thread::ap_ST_st6_fsm_5 = "00101";
const sc_lv<5> matrix_mul_thread::ap_ST_st7_fsm_6 = "00110";
const sc_lv<5> matrix_mul_thread::ap_ST_st8_fsm_7 = "00111";
const sc_lv<5> matrix_mul_thread::ap_ST_st9_fsm_8 = "01000";
const sc_lv<5> matrix_mul_thread::ap_ST_st10_fsm_9 = "01001";
const sc_lv<5> matrix_mul_thread::ap_ST_st11_fsm_10 = "01010";
const sc_lv<5> matrix_mul_thread::ap_ST_st12_fsm_11 = "01011";
const sc_lv<5> matrix_mul_thread::ap_ST_st13_fsm_12 = "01100";
const sc_lv<5> matrix_mul_thread::ap_ST_st14_fsm_13 = "01101";
const sc_lv<5> matrix_mul_thread::ap_ST_st15_fsm_14 = "01110";
const sc_lv<5> matrix_mul_thread::ap_ST_st16_fsm_15 = "01111";
const sc_lv<5> matrix_mul_thread::ap_ST_st17_fsm_16 = "10000";
const sc_lv<5> matrix_mul_thread::ap_ST_st18_fsm_17 = "10001";
const sc_lv<5> matrix_mul_thread::ap_ST_st19_fsm_18 = "10010";
const sc_lv<5> matrix_mul_thread::ap_ST_st20_fsm_19 = "10011";
const sc_lv<5> matrix_mul_thread::ap_ST_st21_fsm_20 = "10100";
const sc_lv<5> matrix_mul_thread::ap_ST_st22_fsm_21 = "10101";
const sc_lv<5> matrix_mul_thread::ap_ST_st23_fsm_22 = "10110";
const sc_lv<5> matrix_mul_thread::ap_ST_st24_fsm_23 = "10111";
const sc_lv<5> matrix_mul_thread::ap_ST_st25_fsm_24 = "11000";
const sc_lv<5> matrix_mul_thread::ap_ST_st26_fsm_25 = "11001";
const sc_lv<5> matrix_mul_thread::ap_ST_st27_fsm_26 = "11010";
const sc_lv<5> matrix_mul_thread::ap_ST_st28_fsm_27 = "11011";
const sc_lv<1> matrix_mul_thread::ap_const_lv1_0 = "0";
const sc_lv<17> matrix_mul_thread::ap_const_lv17_0 = "00000000000000000";
const sc_lv<9> matrix_mul_thread::ap_const_lv9_0 = "000000000";
const sc_lv<32> matrix_mul_thread::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> matrix_mul_thread::ap_const_lv1_1 = "1";
const sc_lv<17> matrix_mul_thread::ap_const_lv17_15F90 = "10101111110010000";
const sc_lv<17> matrix_mul_thread::ap_const_lv17_1 = "00000000000000001";
const sc_lv<17> matrix_mul_thread::ap_const_lv17_15F8F = "10101111110001111";
const sc_lv<17> matrix_mul_thread::ap_const_lv17_12C = "00000000100101100";
const sc_lv<9> matrix_mul_thread::ap_const_lv9_12C = "100101100";
const sc_lv<9> matrix_mul_thread::ap_const_lv9_1 = "000000001";

matrix_mul_thread::matrix_mul_thread(sc_module_name name) : sc_module(name), mVcdFile(0) {
    matrix_mul_mul_32s_32s_32_6_U1 = new matrix_mul_mul_32s_32s_32_6<1,6,32,32,32>("matrix_mul_mul_32s_32s_32_6_U1");
    matrix_mul_mul_32s_32s_32_6_U1->clk(ap_clk);
    matrix_mul_mul_32s_32s_32_6_U1->reset(ap_rst);
    matrix_mul_mul_32s_32s_32_6_U1->din0(grp_fu_515_p0);
    matrix_mul_mul_32s_32s_32_6_U1->din1(grp_fu_515_p1);
    matrix_mul_mul_32s_32s_32_6_U1->ce(grp_fu_515_ce);
    matrix_mul_mul_32s_32s_32_6_U1->dout(grp_fu_515_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ReadEnablePort_0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );

    SC_METHOD(thread_ReadEnablePort_0_ap_vld);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );

    SC_METHOD(thread_WriteDataPort_0);
    sensitive << ( m_result_q0 );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_WriteDataPort_0_ap_vld);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_WriteEnablePort_0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_WriteEnablePort_0_ap_vld);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );
    sensitive << ( exitcond8_fu_466_p2 );
    sensitive << ( grp_wireread_fu_153_p2 );
    sensitive << ( exitcond_fu_367_p2 );
    sensitive << ( exitcond9_fu_450_p2 );
    sensitive << ( exitcond1_fu_400_p2 );
    sensitive << ( exitcond2_fu_434_p2 );
    sensitive << ( exitcond7_fu_529_p2 );

    SC_METHOD(thread_exitcond1_fu_400_p2);
    sensitive << ( i_1_reg_256 );

    SC_METHOD(thread_exitcond2_fu_434_p2);
    sensitive << ( i_2_reg_268 );

    SC_METHOD(thread_exitcond7_fu_529_p2);
    sensitive << ( i_4_reg_349 );

    SC_METHOD(thread_exitcond8_fu_466_p2);
    sensitive << ( k_reg_302 );

    SC_METHOD(thread_exitcond9_fu_450_p2);
    sensitive << ( j_reg_291 );

    SC_METHOD(thread_exitcond_fu_367_p2);
    sensitive << ( i_reg_232 );

    SC_METHOD(thread_grp_fu_515_ce);

    SC_METHOD(thread_grp_fu_515_p0);
    sensitive << ( m_operand2_load_reg_654 );

    SC_METHOD(thread_grp_fu_515_p1);
    sensitive << ( m_operand1_load_reg_649 );

    SC_METHOD(thread_grp_wireread_fu_140_p2);
    sensitive << ( ReadEmptyPort_0 );

    SC_METHOD(thread_grp_wireread_fu_153_p2);
    sensitive << ( WriteFullPort_0 );

    SC_METHOD(thread_i_3_fu_373_p2);
    sensitive << ( i_reg_232 );

    SC_METHOD(thread_i_5_fu_406_p2);
    sensitive << ( i_1_reg_256 );

    SC_METHOD(thread_i_6_fu_440_p2);
    sensitive << ( i_2_reg_268 );

    SC_METHOD(thread_i_7_fu_535_p2);
    sensitive << ( i_4_reg_349 );

    SC_METHOD(thread_j_1_fu_456_p2);
    sensitive << ( j_reg_291 );

    SC_METHOD(thread_j_cast_fu_446_p1);
    sensitive << ( j_reg_291 );

    SC_METHOD(thread_k_1_fu_472_p2);
    sensitive << ( k_reg_302 );

    SC_METHOD(thread_k_cast_fu_462_p1);
    sensitive << ( k_reg_302 );

    SC_METHOD(thread_m_operand1_address0);
    sensitive << ( m_operand1_addr_1_reg_557 );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );
    sensitive << ( exitcond8_fu_466_p2 );
    sensitive << ( tmp_2_cast_fu_484_p1 );

    SC_METHOD(thread_m_operand1_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );
    sensitive << ( exitcond8_fu_466_p2 );

    SC_METHOD(thread_m_operand1_d0);
    sensitive << ( ReadDataPort_0 );

    SC_METHOD(thread_m_operand1_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );

    SC_METHOD(thread_m_operand2_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );
    sensitive << ( m_operand2_addr_1_reg_578 );
    sensitive << ( exitcond8_fu_466_p2 );
    sensitive << ( tmp_5_cast_fu_500_p1 );

    SC_METHOD(thread_m_operand2_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );
    sensitive << ( exitcond8_fu_466_p2 );

    SC_METHOD(thread_m_operand2_d0);
    sensitive << ( ReadDataPort_0 );

    SC_METHOD(thread_m_operand2_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_wireread_fu_140_p2 );

    SC_METHOD(thread_m_result_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond8_fu_466_p2 );
    sensitive << ( m_result_addr_1_reg_669 );
    sensitive << ( grp_wireread_fu_153_p2 );
    sensitive << ( tmp_1_cast_fu_510_p1 );

    SC_METHOD(thread_m_result_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond8_fu_466_p2 );
    sensitive << ( grp_wireread_fu_153_p2 );

    SC_METHOD(thread_m_result_d0);
    sensitive << ( sum_reg_313 );

    SC_METHOD(thread_m_result_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond8_fu_466_p2 );

    SC_METHOD(thread_next_mul1_fu_428_p2);
    sensitive << ( phi_mul1_reg_279 );

    SC_METHOD(thread_next_mul_fu_489_p2);
    sensitive << ( phi_mul_reg_326 );

    SC_METHOD(thread_ptData32_assign_1_rec_cast_fu_362_p1);
    sensitive << ( ptData32_assign_1_rec_reg_220 );

    SC_METHOD(thread_ptData32_assign_3_rec_cast_fu_395_p1);
    sensitive << ( ptData32_assign_3_rec_reg_244 );

    SC_METHOD(thread_ptData32_assign_4_rec_fu_389_p2);
    sensitive << ( ptData32_assign_1_rec_reg_220 );
    sensitive << ( ptData3_0_i_cast_fu_385_p1 );

    SC_METHOD(thread_ptData32_assign_6_rec_cast_fu_524_p1);
    sensitive << ( ptData32_assign_6_rec_reg_337 );

    SC_METHOD(thread_ptData32_assign_7_rec_fu_422_p2);
    sensitive << ( ptData32_assign_3_rec_reg_244 );
    sensitive << ( ptData3_0_i1_cast_fu_418_p1 );

    SC_METHOD(thread_ptData32_assign_8_rec_fu_551_p2);
    sensitive << ( ptData32_assign_6_rec_reg_337 );
    sensitive << ( ptData3_0_i2_cast_fu_547_p1 );

    SC_METHOD(thread_ptData3_0_i1_cast_fu_418_p1);
    sensitive << ( tmp_8_fu_412_p2 );

    SC_METHOD(thread_ptData3_0_i2_cast_fu_547_p1);
    sensitive << ( tmp_s_fu_541_p2 );

    SC_METHOD(thread_ptData3_0_i_cast_fu_385_p1);
    sensitive << ( tmp_3_fu_379_p2 );

    SC_METHOD(thread_sum_1_fu_519_p2);
    sensitive << ( tmp_6_reg_659 );
    sensitive << ( sum_reg_313 );

    SC_METHOD(thread_tmp_1_cast_fu_510_p1);
    sensitive << ( tmp_1_fu_505_p2 );

    SC_METHOD(thread_tmp_1_fu_505_p2);
    sensitive << ( j_cast_reg_612 );
    sensitive << ( phi_mul1_reg_279 );

    SC_METHOD(thread_tmp_2_cast_fu_484_p1);
    sensitive << ( tmp_2_fu_478_p2 );

    SC_METHOD(thread_tmp_2_fu_478_p2);
    sensitive << ( phi_mul1_reg_279 );
    sensitive << ( k_cast_fu_462_p1 );

    SC_METHOD(thread_tmp_3_fu_379_p2);
    sensitive << ( i_reg_232 );

    SC_METHOD(thread_tmp_5_cast_fu_500_p1);
    sensitive << ( tmp_5_fu_495_p2 );

    SC_METHOD(thread_tmp_5_fu_495_p2);
    sensitive << ( j_cast_reg_612 );
    sensitive << ( phi_mul_reg_326 );

    SC_METHOD(thread_tmp_8_fu_412_p2);
    sensitive << ( i_1_reg_256 );

    SC_METHOD(thread_tmp_s_fu_541_p2);
    sensitive << ( i_4_reg_349 );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_mul_thread_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(-12);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ReadEnablePort_0, "(port)ReadEnablePort_0");
    sc_trace(mVcdFile, ReadEnablePort_0_ap_vld, "(port)ReadEnablePort_0_ap_vld");
    sc_trace(mVcdFile, ReadEmptyPort_0, "(port)ReadEmptyPort_0");
    sc_trace(mVcdFile, ReadDataPort_0, "(port)ReadDataPort_0");
    sc_trace(mVcdFile, WriteEnablePort_0, "(port)WriteEnablePort_0");
    sc_trace(mVcdFile, WriteEnablePort_0_ap_vld, "(port)WriteEnablePort_0_ap_vld");
    sc_trace(mVcdFile, WriteFullPort_0, "(port)WriteFullPort_0");
    sc_trace(mVcdFile, WriteDataPort_0, "(port)WriteDataPort_0");
    sc_trace(mVcdFile, WriteDataPort_0_ap_vld, "(port)WriteDataPort_0_ap_vld");
    sc_trace(mVcdFile, m_result_address0, "(port)m_result_address0");
    sc_trace(mVcdFile, m_result_ce0, "(port)m_result_ce0");
    sc_trace(mVcdFile, m_result_we0, "(port)m_result_we0");
    sc_trace(mVcdFile, m_result_d0, "(port)m_result_d0");
    sc_trace(mVcdFile, m_result_q0, "(port)m_result_q0");
    sc_trace(mVcdFile, m_operand1_address0, "(port)m_operand1_address0");
    sc_trace(mVcdFile, m_operand1_ce0, "(port)m_operand1_ce0");
    sc_trace(mVcdFile, m_operand1_we0, "(port)m_operand1_we0");
    sc_trace(mVcdFile, m_operand1_d0, "(port)m_operand1_d0");
    sc_trace(mVcdFile, m_operand1_q0, "(port)m_operand1_q0");
    sc_trace(mVcdFile, m_operand2_address0, "(port)m_operand2_address0");
    sc_trace(mVcdFile, m_operand2_ce0, "(port)m_operand2_ce0");
    sc_trace(mVcdFile, m_operand2_we0, "(port)m_operand2_we0");
    sc_trace(mVcdFile, m_operand2_d0, "(port)m_operand2_d0");
    sc_trace(mVcdFile, m_operand2_q0, "(port)m_operand2_q0");
    sc_trace(mVcdFile, m_operand1_addr_1_reg_557, "m_operand1_addr_1_reg_557");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, i_3_fu_373_p2, "i_3_fu_373_p2");
    sc_trace(mVcdFile, i_3_reg_565, "i_3_reg_565");
    sc_trace(mVcdFile, ptData32_assign_4_rec_fu_389_p2, "ptData32_assign_4_rec_fu_389_p2");
    sc_trace(mVcdFile, ptData32_assign_4_rec_reg_573, "ptData32_assign_4_rec_reg_573");
    sc_trace(mVcdFile, grp_wireread_fu_140_p2, "grp_wireread_fu_140_p2");
    sc_trace(mVcdFile, m_operand2_addr_1_reg_578, "m_operand2_addr_1_reg_578");
    sc_trace(mVcdFile, i_5_fu_406_p2, "i_5_fu_406_p2");
    sc_trace(mVcdFile, i_5_reg_586, "i_5_reg_586");
    sc_trace(mVcdFile, ptData32_assign_7_rec_fu_422_p2, "ptData32_assign_7_rec_fu_422_p2");
    sc_trace(mVcdFile, ptData32_assign_7_rec_reg_594, "ptData32_assign_7_rec_reg_594");
    sc_trace(mVcdFile, next_mul1_fu_428_p2, "next_mul1_fu_428_p2");
    sc_trace(mVcdFile, next_mul1_reg_599, "next_mul1_reg_599");
    sc_trace(mVcdFile, i_6_fu_440_p2, "i_6_fu_440_p2");
    sc_trace(mVcdFile, i_6_reg_607, "i_6_reg_607");
    sc_trace(mVcdFile, j_cast_fu_446_p1, "j_cast_fu_446_p1");
    sc_trace(mVcdFile, j_cast_reg_612, "j_cast_reg_612");
    sc_trace(mVcdFile, j_1_fu_456_p2, "j_1_fu_456_p2");
    sc_trace(mVcdFile, j_1_reg_621, "j_1_reg_621");
    sc_trace(mVcdFile, k_1_fu_472_p2, "k_1_fu_472_p2");
    sc_trace(mVcdFile, k_1_reg_629, "k_1_reg_629");
    sc_trace(mVcdFile, exitcond8_fu_466_p2, "exitcond8_fu_466_p2");
    sc_trace(mVcdFile, next_mul_fu_489_p2, "next_mul_fu_489_p2");
    sc_trace(mVcdFile, next_mul_reg_639, "next_mul_reg_639");
    sc_trace(mVcdFile, m_operand1_load_reg_649, "m_operand1_load_reg_649");
    sc_trace(mVcdFile, m_operand2_load_reg_654, "m_operand2_load_reg_654");
    sc_trace(mVcdFile, grp_fu_515_p2, "grp_fu_515_p2");
    sc_trace(mVcdFile, tmp_6_reg_659, "tmp_6_reg_659");
    sc_trace(mVcdFile, sum_1_fu_519_p2, "sum_1_fu_519_p2");
    sc_trace(mVcdFile, m_result_addr_1_reg_669, "m_result_addr_1_reg_669");
    sc_trace(mVcdFile, i_7_fu_535_p2, "i_7_fu_535_p2");
    sc_trace(mVcdFile, i_7_reg_677, "i_7_reg_677");
    sc_trace(mVcdFile, ptData32_assign_8_rec_fu_551_p2, "ptData32_assign_8_rec_fu_551_p2");
    sc_trace(mVcdFile, ptData32_assign_8_rec_reg_685, "ptData32_assign_8_rec_reg_685");
    sc_trace(mVcdFile, grp_wireread_fu_153_p2, "grp_wireread_fu_153_p2");
    sc_trace(mVcdFile, ptData32_assign_1_rec_reg_220, "ptData32_assign_1_rec_reg_220");
    sc_trace(mVcdFile, i_reg_232, "i_reg_232");
    sc_trace(mVcdFile, ptData32_assign_3_rec_reg_244, "ptData32_assign_3_rec_reg_244");
    sc_trace(mVcdFile, exitcond_fu_367_p2, "exitcond_fu_367_p2");
    sc_trace(mVcdFile, i_1_reg_256, "i_1_reg_256");
    sc_trace(mVcdFile, i_2_reg_268, "i_2_reg_268");
    sc_trace(mVcdFile, exitcond9_fu_450_p2, "exitcond9_fu_450_p2");
    sc_trace(mVcdFile, exitcond1_fu_400_p2, "exitcond1_fu_400_p2");
    sc_trace(mVcdFile, phi_mul1_reg_279, "phi_mul1_reg_279");
    sc_trace(mVcdFile, j_reg_291, "j_reg_291");
    sc_trace(mVcdFile, exitcond2_fu_434_p2, "exitcond2_fu_434_p2");
    sc_trace(mVcdFile, k_reg_302, "k_reg_302");
    sc_trace(mVcdFile, sum_reg_313, "sum_reg_313");
    sc_trace(mVcdFile, phi_mul_reg_326, "phi_mul_reg_326");
    sc_trace(mVcdFile, ptData32_assign_6_rec_reg_337, "ptData32_assign_6_rec_reg_337");
    sc_trace(mVcdFile, i_4_reg_349, "i_4_reg_349");
    sc_trace(mVcdFile, ptData32_assign_1_rec_cast_fu_362_p1, "ptData32_assign_1_rec_cast_fu_362_p1");
    sc_trace(mVcdFile, ptData32_assign_3_rec_cast_fu_395_p1, "ptData32_assign_3_rec_cast_fu_395_p1");
    sc_trace(mVcdFile, tmp_2_cast_fu_484_p1, "tmp_2_cast_fu_484_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_500_p1, "tmp_5_cast_fu_500_p1");
    sc_trace(mVcdFile, tmp_1_cast_fu_510_p1, "tmp_1_cast_fu_510_p1");
    sc_trace(mVcdFile, ptData32_assign_6_rec_cast_fu_524_p1, "ptData32_assign_6_rec_cast_fu_524_p1");
    sc_trace(mVcdFile, tmp_3_fu_379_p2, "tmp_3_fu_379_p2");
    sc_trace(mVcdFile, ptData3_0_i_cast_fu_385_p1, "ptData3_0_i_cast_fu_385_p1");
    sc_trace(mVcdFile, tmp_8_fu_412_p2, "tmp_8_fu_412_p2");
    sc_trace(mVcdFile, ptData3_0_i1_cast_fu_418_p1, "ptData3_0_i1_cast_fu_418_p1");
    sc_trace(mVcdFile, k_cast_fu_462_p1, "k_cast_fu_462_p1");
    sc_trace(mVcdFile, tmp_2_fu_478_p2, "tmp_2_fu_478_p2");
    sc_trace(mVcdFile, tmp_5_fu_495_p2, "tmp_5_fu_495_p2");
    sc_trace(mVcdFile, tmp_1_fu_505_p2, "tmp_1_fu_505_p2");
    sc_trace(mVcdFile, grp_fu_515_p0, "grp_fu_515_p0");
    sc_trace(mVcdFile, grp_fu_515_p1, "grp_fu_515_p1");
    sc_trace(mVcdFile, tmp_s_fu_541_p2, "tmp_s_fu_541_p2");
    sc_trace(mVcdFile, ptData3_0_i2_cast_fu_547_p1, "ptData3_0_i2_cast_fu_547_p1");
    sc_trace(mVcdFile, grp_fu_515_ce, "grp_fu_515_ce");
    sc_trace(mVcdFile, exitcond7_fu_529_p2, "exitcond7_fu_529_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");

    }
    mHdltvinHandle.open("matrix_mul_thread.hdltvin.dat");
    mHdltvoutHandle.open("matrix_mul_thread.hdltvout.dat");
}

matrix_mul_thread::~matrix_mul_thread() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete matrix_mul_mul_32s_32s_32_6_U1;
}

void matrix_mul_thread::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st2_fsm_1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read())) {
        i_1_reg_256 = i_5_reg_586.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_367_p2.read()))) {
        i_1_reg_256 = ap_const_lv17_0;
    }
    if ((esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_400_p2.read()))) {
        i_2_reg_268 = ap_const_lv9_0;
    } else if ((esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_450_p2.read()))) {
        i_2_reg_268 = i_6_reg_607.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read())) {
        i_3_reg_565 = i_3_fu_373_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st28_fsm_27, ap_CS_fsm.read())) {
        i_4_reg_349 = i_7_reg_677.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_434_p2.read()))) {
        i_4_reg_349 = ap_const_lv17_0;
    }
    if (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read())) {
        i_5_reg_586 = i_5_fu_406_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) {
        i_6_reg_607 = i_6_fu_440_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st24_fsm_23, ap_CS_fsm.read())) {
        i_7_reg_677 = i_7_fu_535_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read())) {
        i_reg_232 = i_3_reg_565.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        i_reg_232 = ap_const_lv17_0;
    }
    if (esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read())) {
        j_1_reg_621 = j_1_fu_456_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read())) {
        j_cast_reg_612 = j_cast_fu_446_p1.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_434_p2.read()))) {
        j_reg_291 = ap_const_lv9_0;
    } else if ((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read()))) {
        j_reg_291 = j_1_reg_621.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read())) {
        k_1_reg_629 = k_1_fu_472_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_450_p2.read()))) {
        k_reg_302 = ap_const_lv9_0;
    } else if (esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) {
        k_reg_302 = k_1_reg_629.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read())) {
        m_operand1_addr_1_reg_557 =  (sc_lv<17>) (ptData32_assign_1_rec_cast_fu_362_p1.read());
    }
    if (esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read())) {
        m_operand1_load_reg_649 = m_operand1_q0.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read())) {
        m_operand2_addr_1_reg_578 =  (sc_lv<17>) (ptData32_assign_3_rec_cast_fu_395_p1.read());
    }
    if (esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read())) {
        m_operand2_load_reg_654 = m_operand2_q0.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st24_fsm_23, ap_CS_fsm.read())) {
        m_result_addr_1_reg_669 =  (sc_lv<17>) (ptData32_assign_6_rec_cast_fu_524_p1.read());
    }
    if (esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) {
        next_mul1_reg_599 = next_mul1_fu_428_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read()))) {
        next_mul_reg_639 = next_mul_fu_489_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_400_p2.read()))) {
        phi_mul1_reg_279 = ap_const_lv17_0;
    } else if ((esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_450_p2.read()))) {
        phi_mul1_reg_279 = next_mul1_reg_599.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_450_p2.read()))) {
        phi_mul_reg_326 = ap_const_lv17_0;
    } else if (esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) {
        phi_mul_reg_326 = next_mul_reg_639.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read())) {
        ptData32_assign_1_rec_reg_220 = ptData32_assign_4_rec_reg_573.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        ptData32_assign_1_rec_reg_220 = ap_const_lv17_0;
    }
    if (esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read())) {
        ptData32_assign_3_rec_reg_244 = ptData32_assign_7_rec_reg_594.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_367_p2.read()))) {
        ptData32_assign_3_rec_reg_244 = ap_const_lv17_0;
    }
    if ((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0))) {
        ptData32_assign_4_rec_reg_573 = ptData32_assign_4_rec_fu_389_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st28_fsm_27, ap_CS_fsm.read())) {
        ptData32_assign_6_rec_reg_337 = ptData32_assign_8_rec_reg_685.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_434_p2.read()))) {
        ptData32_assign_6_rec_reg_337 = ap_const_lv17_0;
    }
    if ((esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read()))) {
        ptData32_assign_7_rec_reg_594 = ptData32_assign_7_rec_fu_422_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st25_fsm_24, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, grp_wireread_fu_153_p2.read()))) {
        ptData32_assign_8_rec_reg_685 = ptData32_assign_8_rec_fu_551_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_450_p2.read()))) {
        sum_reg_313 = ap_const_lv32_0;
    } else if (esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read())) {
        sum_reg_313 = sum_1_fu_519_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read())) {
        tmp_6_reg_659 = grp_fu_515_p2.read();
    }
}

void matrix_mul_thread::thread_ReadEnablePort_0() {
    if ((esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st11_fsm_10, ap_CS_fsm.read()))) {
        ReadEnablePort_0 = ap_const_lv1_0;
    } else if (((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read())))) {
        ReadEnablePort_0 = ap_const_lv1_1;
    } else {
        ReadEnablePort_0 = ap_const_lv1_1;
    }
}

void matrix_mul_thread::thread_ReadEnablePort_0_ap_vld() {
    if (((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) || 
         esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st11_fsm_10, ap_CS_fsm.read()))) {
        ReadEnablePort_0_ap_vld = ap_const_logic_1;
    } else {
        ReadEnablePort_0_ap_vld = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_WriteDataPort_0() {
    if (esl_seteq<1,5,5>(ap_ST_st27_fsm_26, ap_CS_fsm.read())) {
        WriteDataPort_0 = ap_const_lv32_0;
    } else if (esl_seteq<1,5,5>(ap_ST_st26_fsm_25, ap_CS_fsm.read())) {
        WriteDataPort_0 = m_result_q0.read();
    } else {
        WriteDataPort_0 = ap_const_lv32_0;
    }
}

void matrix_mul_thread::thread_WriteDataPort_0_ap_vld() {
    if ((esl_seteq<1,5,5>(ap_ST_st26_fsm_25, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st27_fsm_26, ap_CS_fsm.read()))) {
        WriteDataPort_0_ap_vld = ap_const_logic_1;
    } else {
        WriteDataPort_0_ap_vld = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_WriteEnablePort_0() {
    if (esl_seteq<1,5,5>(ap_ST_st27_fsm_26, ap_CS_fsm.read())) {
        WriteEnablePort_0 = ap_const_lv1_0;
    } else if (esl_seteq<1,5,5>(ap_ST_st26_fsm_25, ap_CS_fsm.read())) {
        WriteEnablePort_0 = ap_const_lv1_1;
    } else {
        WriteEnablePort_0 = ap_const_lv1_1;
    }
}

void matrix_mul_thread::thread_WriteEnablePort_0_ap_vld() {
    if ((esl_seteq<1,5,5>(ap_ST_st26_fsm_25, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st27_fsm_26, ap_CS_fsm.read()))) {
        WriteEnablePort_0_ap_vld = ap_const_logic_1;
    } else {
        WriteEnablePort_0_ap_vld = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_ap_NS_fsm() {
    if (esl_seteq<1,5,5>(ap_ST_st27_fsm_26, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st28_fsm_27;
    } else if (esl_seteq<1,5,5>(ap_ST_st26_fsm_25, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st27_fsm_26;
    } else if ((esl_seteq<1,5,5>(ap_ST_st25_fsm_24, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, grp_wireread_fu_153_p2.read()))) {
        ap_NS_fsm = ap_ST_st26_fsm_25;
    } else if (((esl_seteq<1,5,5>(ap_ST_st24_fsm_23, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_529_p2.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st25_fsm_24, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, grp_wireread_fu_153_p2.read())))) {
        ap_NS_fsm = ap_ST_st25_fsm_24;
    } else if (esl_seteq<1,5,5>(ap_ST_st22_fsm_21, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st23_fsm_22;
    } else if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st22_fsm_21;
    } else if (esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st21_fsm_20;
    } else if (esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st20_fsm_19;
    } else if (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st19_fsm_18;
    } else if (esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st18_fsm_17;
    } else if (esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st17_fsm_16;
    } else if ((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read()))) {
        ap_NS_fsm = ap_ST_st16_fsm_15;
    } else if ((esl_seteq<1,5,5>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) || 
                (esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_450_p2.read())))) {
        ap_NS_fsm = ap_ST_st15_fsm_14;
    } else if (((esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_434_p2.read())) || 
                esl_seteq<1,5,5>(ap_ST_st28_fsm_27, ap_CS_fsm.read()))) {
        ap_NS_fsm = ap_ST_st24_fsm_23;
    } else if (((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st13_fsm_12, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_434_p2.read())))) {
        ap_NS_fsm = ap_ST_st14_fsm_13;
    } else if (esl_seteq<1,5,5>(ap_ST_st11_fsm_10, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st12_fsm_11;
    } else if ((esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read()))) {
        ap_NS_fsm = ap_ST_st11_fsm_10;
    } else if (((esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_450_p2.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_400_p2.read())))) {
        ap_NS_fsm = ap_ST_st13_fsm_12;
    } else if (((esl_seteq<1,5,5>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_400_p2.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0)))) {
        ap_NS_fsm = ap_ST_st10_fsm_9;
    } else if (esl_seteq<1,5,5>(ap_ST_st7_fsm_6, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st8_fsm_7;
    } else if ((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0))) {
        ap_NS_fsm = ap_ST_st7_fsm_6;
    } else if (((esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_367_p2.read())) || 
                esl_seteq<1,5,5>(ap_ST_st12_fsm_11, ap_CS_fsm.read()))) {
        ap_NS_fsm = ap_ST_st9_fsm_8;
    } else if (((esl_seteq<1,5,5>(ap_ST_st5_fsm_4, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_367_p2.read())) || 
                (esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0)))) {
        ap_NS_fsm = ap_ST_st6_fsm_5;
    } else if ((esl_seteq<1,5,5>(ap_ST_st4_fsm_3, ap_CS_fsm.read()) || 
                esl_seteq<1,5,5>(ap_ST_st8_fsm_7, ap_CS_fsm.read()))) {
        ap_NS_fsm = ap_ST_st5_fsm_4;
    } else if ((esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) || 
                (esl_seteq<1,5,5>(ap_ST_st24_fsm_23, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_529_p2.read())))) {
        ap_NS_fsm = ap_ST_st4_fsm_3;
    } else if (esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        ap_NS_fsm = ap_ST_st3_fsm_2;
    } else {
        ap_NS_fsm = ap_CS_fsm.read();
    }
}

void matrix_mul_thread::thread_exitcond1_fu_400_p2() {
    exitcond1_fu_400_p2 = (!i_1_reg_256.read().is_01() || !ap_const_lv17_15F90.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_256.read() == ap_const_lv17_15F90);
}

void matrix_mul_thread::thread_exitcond2_fu_434_p2() {
    exitcond2_fu_434_p2 = (!i_2_reg_268.read().is_01() || !ap_const_lv9_12C.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_268.read() == ap_const_lv9_12C);
}

void matrix_mul_thread::thread_exitcond7_fu_529_p2() {
    exitcond7_fu_529_p2 = (!i_4_reg_349.read().is_01() || !ap_const_lv17_15F90.is_01())? sc_lv<1>(): sc_lv<1>(i_4_reg_349.read() == ap_const_lv17_15F90);
}

void matrix_mul_thread::thread_exitcond8_fu_466_p2() {
    exitcond8_fu_466_p2 = (!k_reg_302.read().is_01() || !ap_const_lv9_12C.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_302.read() == ap_const_lv9_12C);
}

void matrix_mul_thread::thread_exitcond9_fu_450_p2() {
    exitcond9_fu_450_p2 = (!j_reg_291.read().is_01() || !ap_const_lv9_12C.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_291.read() == ap_const_lv9_12C);
}

void matrix_mul_thread::thread_exitcond_fu_367_p2() {
    exitcond_fu_367_p2 = (!i_reg_232.read().is_01() || !ap_const_lv17_15F90.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_232.read() == ap_const_lv17_15F90);
}

void matrix_mul_thread::thread_grp_fu_515_ce() {
    grp_fu_515_ce = ap_const_logic_1;
}

void matrix_mul_thread::thread_grp_fu_515_p0() {
    grp_fu_515_p0 = m_operand2_load_reg_654.read();
}

void matrix_mul_thread::thread_grp_fu_515_p1() {
    grp_fu_515_p1 = m_operand1_load_reg_649.read();
}

void matrix_mul_thread::thread_grp_wireread_fu_140_p2() {
    grp_wireread_fu_140_p2 = ReadEmptyPort_0.read();
}

void matrix_mul_thread::thread_grp_wireread_fu_153_p2() {
    grp_wireread_fu_153_p2 = WriteFullPort_0.read();
}

void matrix_mul_thread::thread_i_3_fu_373_p2() {
    i_3_fu_373_p2 = (!i_reg_232.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_bigint<17>(i_reg_232.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void matrix_mul_thread::thread_i_5_fu_406_p2() {
    i_5_fu_406_p2 = (!i_1_reg_256.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_bigint<17>(i_1_reg_256.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void matrix_mul_thread::thread_i_6_fu_440_p2() {
    i_6_fu_440_p2 = (!i_2_reg_268.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_bigint<9>(i_2_reg_268.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void matrix_mul_thread::thread_i_7_fu_535_p2() {
    i_7_fu_535_p2 = (!i_4_reg_349.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_bigint<17>(i_4_reg_349.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void matrix_mul_thread::thread_j_1_fu_456_p2() {
    j_1_fu_456_p2 = (!j_reg_291.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_bigint<9>(j_reg_291.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void matrix_mul_thread::thread_j_cast_fu_446_p1() {
    j_cast_fu_446_p1 = esl_zext<17,9>(j_reg_291.read());
}

void matrix_mul_thread::thread_k_1_fu_472_p2() {
    k_1_fu_472_p2 = (!k_reg_302.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_bigint<9>(k_reg_302.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void matrix_mul_thread::thread_k_cast_fu_462_p1() {
    k_cast_fu_462_p1 = esl_zext<17,9>(k_reg_302.read());
}

void matrix_mul_thread::thread_m_operand1_address0() {
    if ((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0))) {
        m_operand1_address0 = m_operand1_addr_1_reg_557.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read()))) {
        m_operand1_address0 =  (sc_lv<17>) (tmp_2_cast_fu_484_p1.read());
    } else {
        m_operand1_address0 =  (sc_lv<17>) (tmp_2_cast_fu_484_p1.read());
    }
}

void matrix_mul_thread::thread_m_operand1_ce0() {
    if (((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read())))) {
        m_operand1_ce0 = ap_const_logic_1;
    } else {
        m_operand1_ce0 = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_m_operand1_d0() {
    m_operand1_d0 = ReadDataPort_0.read();
}

void matrix_mul_thread::thread_m_operand1_we0() {
    if (((esl_seteq<1,5,5>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0)))) {
        m_operand1_we0 = ap_const_logic_1;
    } else {
        m_operand1_we0 = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_m_operand2_address0() {
    if ((esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read()))) {
        m_operand2_address0 = m_operand2_addr_1_reg_578.read();
    } else if ((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read()))) {
        m_operand2_address0 =  (sc_lv<17>) (tmp_5_cast_fu_500_p1.read());
    } else {
        m_operand2_address0 =  (sc_lv<17>) (tmp_5_cast_fu_500_p1.read());
    }
}

void matrix_mul_thread::thread_m_operand2_ce0() {
    if (((esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read())))) {
        m_operand2_ce0 = ap_const_logic_1;
    } else {
        m_operand2_ce0 = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_m_operand2_d0() {
    m_operand2_d0 = ReadDataPort_0.read();
}

void matrix_mul_thread::thread_m_operand2_we0() {
    if (((esl_seteq<1,1,1>(grp_wireread_fu_140_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,5,5>(ap_ST_st10_fsm_9, ap_CS_fsm.read())))) {
        m_operand2_we0 = ap_const_logic_1;
    } else {
        m_operand2_we0 = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_m_result_address0() {
    if ((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read()))) {
        m_result_address0 =  (sc_lv<17>) (tmp_1_cast_fu_510_p1.read());
    } else if ((esl_seteq<1,5,5>(ap_ST_st25_fsm_24, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, grp_wireread_fu_153_p2.read()))) {
        m_result_address0 = m_result_addr_1_reg_669.read();
    } else {
        m_result_address0 =  (sc_lv<17>) (tmp_1_cast_fu_510_p1.read());
    }
}

void matrix_mul_thread::thread_m_result_ce0() {
    if (((esl_seteq<1,5,5>(ap_ST_st25_fsm_24, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, grp_wireread_fu_153_p2.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read())))) {
        m_result_ce0 = ap_const_logic_1;
    } else {
        m_result_ce0 = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_m_result_d0() {
    m_result_d0 = sum_reg_313.read();
}

void matrix_mul_thread::thread_m_result_we0() {
    if (((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_466_p2.read())))) {
        m_result_we0 = ap_const_logic_1;
    } else {
        m_result_we0 = ap_const_logic_0;
    }
}

void matrix_mul_thread::thread_next_mul1_fu_428_p2() {
    next_mul1_fu_428_p2 = (!phi_mul1_reg_279.read().is_01() || !ap_const_lv17_12C.is_01())? sc_lv<17>(): (sc_bigint<17>(phi_mul1_reg_279.read()) + sc_biguint<17>(ap_const_lv17_12C));
}

void matrix_mul_thread::thread_next_mul_fu_489_p2() {
    next_mul_fu_489_p2 = (!phi_mul_reg_326.read().is_01() || !ap_const_lv17_12C.is_01())? sc_lv<17>(): (sc_bigint<17>(phi_mul_reg_326.read()) + sc_biguint<17>(ap_const_lv17_12C));
}

void matrix_mul_thread::thread_ptData32_assign_1_rec_cast_fu_362_p1() {
    ptData32_assign_1_rec_cast_fu_362_p1 = esl_zext<32,17>(ptData32_assign_1_rec_reg_220.read());
}

void matrix_mul_thread::thread_ptData32_assign_3_rec_cast_fu_395_p1() {
    ptData32_assign_3_rec_cast_fu_395_p1 = esl_zext<32,17>(ptData32_assign_3_rec_reg_244.read());
}

void matrix_mul_thread::thread_ptData32_assign_4_rec_fu_389_p2() {
    ptData32_assign_4_rec_fu_389_p2 = (!ptData32_assign_1_rec_reg_220.read().is_01() || !ptData3_0_i_cast_fu_385_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(ptData32_assign_1_rec_reg_220.read()) + sc_biguint<17>(ptData3_0_i_cast_fu_385_p1.read()));
}

void matrix_mul_thread::thread_ptData32_assign_6_rec_cast_fu_524_p1() {
    ptData32_assign_6_rec_cast_fu_524_p1 = esl_zext<32,17>(ptData32_assign_6_rec_reg_337.read());
}

void matrix_mul_thread::thread_ptData32_assign_7_rec_fu_422_p2() {
    ptData32_assign_7_rec_fu_422_p2 = (!ptData32_assign_3_rec_reg_244.read().is_01() || !ptData3_0_i1_cast_fu_418_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(ptData32_assign_3_rec_reg_244.read()) + sc_biguint<17>(ptData3_0_i1_cast_fu_418_p1.read()));
}

void matrix_mul_thread::thread_ptData32_assign_8_rec_fu_551_p2() {
    ptData32_assign_8_rec_fu_551_p2 = (!ptData32_assign_6_rec_reg_337.read().is_01() || !ptData3_0_i2_cast_fu_547_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(ptData32_assign_6_rec_reg_337.read()) + sc_biguint<17>(ptData3_0_i2_cast_fu_547_p1.read()));
}

void matrix_mul_thread::thread_ptData3_0_i1_cast_fu_418_p1() {
    ptData3_0_i1_cast_fu_418_p1 = esl_zext<17,1>(tmp_8_fu_412_p2.read());
}

void matrix_mul_thread::thread_ptData3_0_i2_cast_fu_547_p1() {
    ptData3_0_i2_cast_fu_547_p1 = esl_zext<17,1>(tmp_s_fu_541_p2.read());
}

void matrix_mul_thread::thread_ptData3_0_i_cast_fu_385_p1() {
    ptData3_0_i_cast_fu_385_p1 = esl_zext<17,1>(tmp_3_fu_379_p2.read());
}

void matrix_mul_thread::thread_sum_1_fu_519_p2() {
    sum_1_fu_519_p2 = (!tmp_6_reg_659.read().is_01() || !sum_reg_313.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_6_reg_659.read()) + sc_biguint<32>(sum_reg_313.read()));
}

void matrix_mul_thread::thread_tmp_1_cast_fu_510_p1() {
    tmp_1_cast_fu_510_p1 = esl_zext<32,17>(tmp_1_fu_505_p2.read());
}

void matrix_mul_thread::thread_tmp_1_fu_505_p2() {
    tmp_1_fu_505_p2 = (!j_cast_reg_612.read().is_01() || !phi_mul1_reg_279.read().is_01())? sc_lv<17>(): (sc_bigint<17>(j_cast_reg_612.read()) + sc_biguint<17>(phi_mul1_reg_279.read()));
}

void matrix_mul_thread::thread_tmp_2_cast_fu_484_p1() {
    tmp_2_cast_fu_484_p1 = esl_zext<32,17>(tmp_2_fu_478_p2.read());
}

void matrix_mul_thread::thread_tmp_2_fu_478_p2() {
    tmp_2_fu_478_p2 = (!k_cast_fu_462_p1.read().is_01() || !phi_mul1_reg_279.read().is_01())? sc_lv<17>(): (sc_bigint<17>(k_cast_fu_462_p1.read()) + sc_biguint<17>(phi_mul1_reg_279.read()));
}

void matrix_mul_thread::thread_tmp_3_fu_379_p2() {
    tmp_3_fu_379_p2 = (!i_reg_232.read().is_01() || !ap_const_lv17_15F8F.is_01())? sc_lv<1>(): (sc_biguint<17>(i_reg_232.read()) < sc_biguint<17>(ap_const_lv17_15F8F));
}

void matrix_mul_thread::thread_tmp_5_cast_fu_500_p1() {
    tmp_5_cast_fu_500_p1 = esl_zext<32,17>(tmp_5_fu_495_p2.read());
}

void matrix_mul_thread::thread_tmp_5_fu_495_p2() {
    tmp_5_fu_495_p2 = (!phi_mul_reg_326.read().is_01() || !j_cast_reg_612.read().is_01())? sc_lv<17>(): (sc_bigint<17>(phi_mul_reg_326.read()) + sc_biguint<17>(j_cast_reg_612.read()));
}

void matrix_mul_thread::thread_tmp_8_fu_412_p2() {
    tmp_8_fu_412_p2 = (!i_1_reg_256.read().is_01() || !ap_const_lv17_15F8F.is_01())? sc_lv<1>(): (sc_biguint<17>(i_1_reg_256.read()) < sc_biguint<17>(ap_const_lv17_15F8F));
}

void matrix_mul_thread::thread_tmp_s_fu_541_p2() {
    tmp_s_fu_541_p2 = (!i_4_reg_349.read().is_01() || !ap_const_lv17_15F8F.is_01())? sc_lv<1>(): (sc_biguint<17>(i_4_reg_349.read()) < sc_biguint<17>(ap_const_lv17_15F8F));
}

}

