// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2012.4
// Copyright (C) 2012 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "matrix_mul.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_mul::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> matrix_mul::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_mul::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_logic matrix_mul::ap_const_logic_0 = sc_dt::Log_0;

matrix_mul::matrix_mul(sc_module_name name) : sc_module(name), mVcdFile(0) {
    m_result_U = new matrix_mul_m_result("m_result_U");
    m_result_U->clk(ClockPort);
    m_result_U->reset(nResetPort);
    m_result_U->address0(m_result_address0);
    m_result_U->ce0(m_result_ce0);
    m_result_U->we0(m_result_we0);
    m_result_U->d0(m_result_d0);
    m_result_U->q0(m_result_q0);
    m_operand1_U = new matrix_mul_m_result("m_operand1_U");
    m_operand1_U->clk(ClockPort);
    m_operand1_U->reset(nResetPort);
    m_operand1_U->address0(m_operand1_address0);
    m_operand1_U->ce0(m_operand1_ce0);
    m_operand1_U->we0(m_operand1_we0);
    m_operand1_U->d0(m_operand1_d0);
    m_operand1_U->q0(m_operand1_q0);
    m_operand2_U = new matrix_mul_m_result("m_operand2_U");
    m_operand2_U->clk(ClockPort);
    m_operand2_U->reset(nResetPort);
    m_operand2_U->address0(m_operand2_address0);
    m_operand2_U->ce0(m_operand2_ce0);
    m_operand2_U->we0(m_operand2_we0);
    m_operand2_U->d0(m_operand2_d0);
    m_operand2_U->q0(m_operand2_q0);
    grp_matrix_mul_thread_fu_74 = new matrix_mul_thread("grp_matrix_mul_thread_fu_74");
    grp_matrix_mul_thread_fu_74->ap_clk(ClockPort);
    grp_matrix_mul_thread_fu_74->ap_rst(nResetPort);
    grp_matrix_mul_thread_fu_74->ReadEnablePort_0(grp_matrix_mul_thread_fu_74_ReadEnablePort_0);
    grp_matrix_mul_thread_fu_74->ReadEnablePort_0_ap_vld(grp_matrix_mul_thread_fu_74_ReadEnablePort_0_ap_vld);
    grp_matrix_mul_thread_fu_74->ReadEmptyPort_0(grp_matrix_mul_thread_fu_74_ReadEmptyPort_0);
    grp_matrix_mul_thread_fu_74->ReadDataPort_0(grp_matrix_mul_thread_fu_74_ReadDataPort_0);
    grp_matrix_mul_thread_fu_74->WriteEnablePort_0(grp_matrix_mul_thread_fu_74_WriteEnablePort_0);
    grp_matrix_mul_thread_fu_74->WriteEnablePort_0_ap_vld(grp_matrix_mul_thread_fu_74_WriteEnablePort_0_ap_vld);
    grp_matrix_mul_thread_fu_74->WriteFullPort_0(grp_matrix_mul_thread_fu_74_WriteFullPort_0);
    grp_matrix_mul_thread_fu_74->WriteDataPort_0(grp_matrix_mul_thread_fu_74_WriteDataPort_0);
    grp_matrix_mul_thread_fu_74->WriteDataPort_0_ap_vld(grp_matrix_mul_thread_fu_74_WriteDataPort_0_ap_vld);
    grp_matrix_mul_thread_fu_74->m_result_address0(grp_matrix_mul_thread_fu_74_m_result_address0);
    grp_matrix_mul_thread_fu_74->m_result_ce0(grp_matrix_mul_thread_fu_74_m_result_ce0);
    grp_matrix_mul_thread_fu_74->m_result_we0(grp_matrix_mul_thread_fu_74_m_result_we0);
    grp_matrix_mul_thread_fu_74->m_result_d0(grp_matrix_mul_thread_fu_74_m_result_d0);
    grp_matrix_mul_thread_fu_74->m_result_q0(grp_matrix_mul_thread_fu_74_m_result_q0);
    grp_matrix_mul_thread_fu_74->m_operand1_address0(grp_matrix_mul_thread_fu_74_m_operand1_address0);
    grp_matrix_mul_thread_fu_74->m_operand1_ce0(grp_matrix_mul_thread_fu_74_m_operand1_ce0);
    grp_matrix_mul_thread_fu_74->m_operand1_we0(grp_matrix_mul_thread_fu_74_m_operand1_we0);
    grp_matrix_mul_thread_fu_74->m_operand1_d0(grp_matrix_mul_thread_fu_74_m_operand1_d0);
    grp_matrix_mul_thread_fu_74->m_operand1_q0(grp_matrix_mul_thread_fu_74_m_operand1_q0);
    grp_matrix_mul_thread_fu_74->m_operand2_address0(grp_matrix_mul_thread_fu_74_m_operand2_address0);
    grp_matrix_mul_thread_fu_74->m_operand2_ce0(grp_matrix_mul_thread_fu_74_m_operand2_ce0);
    grp_matrix_mul_thread_fu_74->m_operand2_we0(grp_matrix_mul_thread_fu_74_m_operand2_we0);
    grp_matrix_mul_thread_fu_74->m_operand2_d0(grp_matrix_mul_thread_fu_74_m_operand2_d0);
    grp_matrix_mul_thread_fu_74->m_operand2_q0(grp_matrix_mul_thread_fu_74_m_operand2_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ClockPort.pos() );

    SC_METHOD(thread_grp_matrix_mul_thread_fu_74_ReadDataPort_0);
    sensitive << ( ReadDataPort_0 );

    SC_METHOD(thread_grp_matrix_mul_thread_fu_74_ReadEmptyPort_0);
    sensitive << ( ReadEmptyPort_0 );

    SC_METHOD(thread_grp_matrix_mul_thread_fu_74_WriteFullPort_0);
    sensitive << ( WriteFullPort_0 );

    SC_METHOD(thread_grp_matrix_mul_thread_fu_74_m_operand1_q0);
    sensitive << ( m_operand1_q0 );

    SC_METHOD(thread_grp_matrix_mul_thread_fu_74_m_operand2_q0);
    sensitive << ( m_operand2_q0 );

    SC_METHOD(thread_grp_matrix_mul_thread_fu_74_m_result_q0);
    sensitive << ( m_result_q0 );

    SC_METHOD(thread_m_operand1_address0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_operand1_address0 );

    SC_METHOD(thread_m_operand1_ce0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_operand1_ce0 );

    SC_METHOD(thread_m_operand1_d0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_operand1_d0 );

    SC_METHOD(thread_m_operand1_we0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_operand1_we0 );

    SC_METHOD(thread_m_operand2_address0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_operand2_address0 );

    SC_METHOD(thread_m_operand2_ce0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_operand2_ce0 );

    SC_METHOD(thread_m_operand2_d0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_operand2_d0 );

    SC_METHOD(thread_m_operand2_we0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_operand2_we0 );

    SC_METHOD(thread_m_result_address0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_result_address0 );

    SC_METHOD(thread_m_result_ce0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_result_ce0 );

    SC_METHOD(thread_m_result_d0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_result_d0 );

    SC_METHOD(thread_m_result_we0);
    sensitive << ( grp_matrix_mul_thread_fu_74_m_result_we0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ClockPort.pos() );

    ReadEnablePort_0.initialize("0");
    WriteEnablePort_0.initialize("0");
    WriteDataPort_0.initialize("00000000000000000000000000000000");
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_mul_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(-12);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, nResetPort, "(port)nResetPort");
    sc_trace(mVcdFile, ClockPort, "(port)ClockPort");
    sc_trace(mVcdFile, ReadEnablePort_0, "(port)ReadEnablePort_0");
    sc_trace(mVcdFile, ReadEmptyPort_0, "(port)ReadEmptyPort_0");
    sc_trace(mVcdFile, ReadDataPort_0, "(port)ReadDataPort_0");
    sc_trace(mVcdFile, WriteEnablePort_0, "(port)WriteEnablePort_0");
    sc_trace(mVcdFile, WriteFullPort_0, "(port)WriteFullPort_0");
    sc_trace(mVcdFile, WriteDataPort_0, "(port)WriteDataPort_0");
    sc_trace(mVcdFile, m_result_address0, "m_result_address0");
    sc_trace(mVcdFile, m_result_ce0, "m_result_ce0");
    sc_trace(mVcdFile, m_result_we0, "m_result_we0");
    sc_trace(mVcdFile, m_result_d0, "m_result_d0");
    sc_trace(mVcdFile, m_result_q0, "m_result_q0");
    sc_trace(mVcdFile, m_operand1_address0, "m_operand1_address0");
    sc_trace(mVcdFile, m_operand1_ce0, "m_operand1_ce0");
    sc_trace(mVcdFile, m_operand1_we0, "m_operand1_we0");
    sc_trace(mVcdFile, m_operand1_d0, "m_operand1_d0");
    sc_trace(mVcdFile, m_operand1_q0, "m_operand1_q0");
    sc_trace(mVcdFile, m_operand2_address0, "m_operand2_address0");
    sc_trace(mVcdFile, m_operand2_ce0, "m_operand2_ce0");
    sc_trace(mVcdFile, m_operand2_we0, "m_operand2_we0");
    sc_trace(mVcdFile, m_operand2_d0, "m_operand2_d0");
    sc_trace(mVcdFile, m_operand2_q0, "m_operand2_q0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_ReadEnablePort_0, "grp_matrix_mul_thread_fu_74_ReadEnablePort_0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_ReadEnablePort_0_ap_vld, "grp_matrix_mul_thread_fu_74_ReadEnablePort_0_ap_vld");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_ReadEmptyPort_0, "grp_matrix_mul_thread_fu_74_ReadEmptyPort_0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_ReadDataPort_0, "grp_matrix_mul_thread_fu_74_ReadDataPort_0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_WriteEnablePort_0, "grp_matrix_mul_thread_fu_74_WriteEnablePort_0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_WriteEnablePort_0_ap_vld, "grp_matrix_mul_thread_fu_74_WriteEnablePort_0_ap_vld");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_WriteFullPort_0, "grp_matrix_mul_thread_fu_74_WriteFullPort_0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_WriteDataPort_0, "grp_matrix_mul_thread_fu_74_WriteDataPort_0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_WriteDataPort_0_ap_vld, "grp_matrix_mul_thread_fu_74_WriteDataPort_0_ap_vld");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_result_address0, "grp_matrix_mul_thread_fu_74_m_result_address0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_result_ce0, "grp_matrix_mul_thread_fu_74_m_result_ce0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_result_we0, "grp_matrix_mul_thread_fu_74_m_result_we0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_result_d0, "grp_matrix_mul_thread_fu_74_m_result_d0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_result_q0, "grp_matrix_mul_thread_fu_74_m_result_q0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand1_address0, "grp_matrix_mul_thread_fu_74_m_operand1_address0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand1_ce0, "grp_matrix_mul_thread_fu_74_m_operand1_ce0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand1_we0, "grp_matrix_mul_thread_fu_74_m_operand1_we0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand1_d0, "grp_matrix_mul_thread_fu_74_m_operand1_d0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand1_q0, "grp_matrix_mul_thread_fu_74_m_operand1_q0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand2_address0, "grp_matrix_mul_thread_fu_74_m_operand2_address0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand2_ce0, "grp_matrix_mul_thread_fu_74_m_operand2_ce0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand2_we0, "grp_matrix_mul_thread_fu_74_m_operand2_we0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand2_d0, "grp_matrix_mul_thread_fu_74_m_operand2_d0");
    sc_trace(mVcdFile, grp_matrix_mul_thread_fu_74_m_operand2_q0, "grp_matrix_mul_thread_fu_74_m_operand2_q0");

    }
    mHdltvinHandle.open("matrix_mul.hdltvin.dat");
    mHdltvoutHandle.open("matrix_mul.hdltvout.dat");
}

matrix_mul::~matrix_mul() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete m_result_U;
    delete m_operand1_U;
    delete m_operand2_U;
    delete grp_matrix_mul_thread_fu_74;
}

void matrix_mul::thread_ap_clk_no_reset_() {
    if ( nResetPort.read() == ap_const_logic_1) {
        ReadEnablePort_0 = ap_const_lv1_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, grp_matrix_mul_thread_fu_74_ReadEnablePort_0_ap_vld.read())) {
            ReadEnablePort_0 = grp_matrix_mul_thread_fu_74_ReadEnablePort_0.read();
        }
    }
    if ( nResetPort.read() == ap_const_logic_1) {
        WriteDataPort_0 = ap_const_lv32_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, grp_matrix_mul_thread_fu_74_WriteDataPort_0_ap_vld.read())) {
            WriteDataPort_0 = grp_matrix_mul_thread_fu_74_WriteDataPort_0.read();
        }
    }
    if ( nResetPort.read() == ap_const_logic_1) {
        WriteEnablePort_0 = ap_const_lv1_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, grp_matrix_mul_thread_fu_74_WriteEnablePort_0_ap_vld.read())) {
            WriteEnablePort_0 = grp_matrix_mul_thread_fu_74_WriteEnablePort_0.read();
        }
    }
}

void matrix_mul::thread_grp_matrix_mul_thread_fu_74_ReadDataPort_0() {
    grp_matrix_mul_thread_fu_74_ReadDataPort_0 = ReadDataPort_0.read();
}

void matrix_mul::thread_grp_matrix_mul_thread_fu_74_ReadEmptyPort_0() {
    grp_matrix_mul_thread_fu_74_ReadEmptyPort_0 = ReadEmptyPort_0.read();
}

void matrix_mul::thread_grp_matrix_mul_thread_fu_74_WriteFullPort_0() {
    grp_matrix_mul_thread_fu_74_WriteFullPort_0 = WriteFullPort_0.read();
}

void matrix_mul::thread_grp_matrix_mul_thread_fu_74_m_operand1_q0() {
    grp_matrix_mul_thread_fu_74_m_operand1_q0 = m_operand1_q0.read();
}

void matrix_mul::thread_grp_matrix_mul_thread_fu_74_m_operand2_q0() {
    grp_matrix_mul_thread_fu_74_m_operand2_q0 = m_operand2_q0.read();
}

void matrix_mul::thread_grp_matrix_mul_thread_fu_74_m_result_q0() {
    grp_matrix_mul_thread_fu_74_m_result_q0 = m_result_q0.read();
}

void matrix_mul::thread_m_operand1_address0() {
    m_operand1_address0 = grp_matrix_mul_thread_fu_74_m_operand1_address0.read();
}

void matrix_mul::thread_m_operand1_ce0() {
    m_operand1_ce0 = grp_matrix_mul_thread_fu_74_m_operand1_ce0.read();
}

void matrix_mul::thread_m_operand1_d0() {
    m_operand1_d0 = grp_matrix_mul_thread_fu_74_m_operand1_d0.read();
}

void matrix_mul::thread_m_operand1_we0() {
    m_operand1_we0 = grp_matrix_mul_thread_fu_74_m_operand1_we0.read();
}

void matrix_mul::thread_m_operand2_address0() {
    m_operand2_address0 = grp_matrix_mul_thread_fu_74_m_operand2_address0.read();
}

void matrix_mul::thread_m_operand2_ce0() {
    m_operand2_ce0 = grp_matrix_mul_thread_fu_74_m_operand2_ce0.read();
}

void matrix_mul::thread_m_operand2_d0() {
    m_operand2_d0 = grp_matrix_mul_thread_fu_74_m_operand2_d0.read();
}

void matrix_mul::thread_m_operand2_we0() {
    m_operand2_we0 = grp_matrix_mul_thread_fu_74_m_operand2_we0.read();
}

void matrix_mul::thread_m_result_address0() {
    m_result_address0 = grp_matrix_mul_thread_fu_74_m_result_address0.read();
}

void matrix_mul::thread_m_result_ce0() {
    m_result_ce0 = grp_matrix_mul_thread_fu_74_m_result_ce0.read();
}

void matrix_mul::thread_m_result_d0() {
    m_result_d0 = grp_matrix_mul_thread_fu_74_m_result_d0.read();
}

void matrix_mul::thread_m_result_we0() {
    m_result_we0 = grp_matrix_mul_thread_fu_74_m_result_we0.read();
}

void matrix_mul::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    ofstream mAeslHdltvinHandle("matrix_mul.autohdltvin.dat");
    ofstream mAeslHdltvoutHandle("matrix_mul.autohdltvout.dat");
    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        mAeslHdltvinHandle << "[[cycle]] " << ap_cycleNo << endl;
        mAeslHdltvoutHandle << "[[cycle]] " << ap_cycleNo << endl;
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mAeslHdltvinHandle << "[nResetPort]" << endl;
        mAeslHdltvinHandle << nResetPort.read() << endl;
        mAeslHdltvinHandle << "[/nResetPort]" << endl;
        mHdltvinHandle << mComma << "{"  <<  " \"nResetPort\" :  \"" << nResetPort.read() << "\" ";
        mAeslHdltvoutHandle << "[ReadEnablePort_0]" << endl;
        mAeslHdltvoutHandle << ReadEnablePort_0.read() << endl;
        mAeslHdltvoutHandle << "[/ReadEnablePort_0]" << endl;
        mHdltvoutHandle << mComma << "{"  <<  " \"ReadEnablePort_0\" :  \"" << ReadEnablePort_0.read() << "\" ";
        mAeslHdltvinHandle << "[ReadEmptyPort_0]" << endl;
        mAeslHdltvinHandle << ReadEmptyPort_0.read() << endl;
        mAeslHdltvinHandle << "[/ReadEmptyPort_0]" << endl;
        mHdltvinHandle << " , " <<  " \"ReadEmptyPort_0\" :  \"" << ReadEmptyPort_0.read() << "\" ";
        mAeslHdltvinHandle << "[ReadDataPort_0]" << endl;
        mAeslHdltvinHandle << ReadDataPort_0.read() << endl;
        mAeslHdltvinHandle << "[/ReadDataPort_0]" << endl;
        mHdltvinHandle << " , " <<  " \"ReadDataPort_0\" :  \"" << ReadDataPort_0.read() << "\" ";
        mAeslHdltvoutHandle << "[WriteEnablePort_0]" << endl;
        mAeslHdltvoutHandle << WriteEnablePort_0.read() << endl;
        mAeslHdltvoutHandle << "[/WriteEnablePort_0]" << endl;
        mHdltvoutHandle << " , " <<  " \"WriteEnablePort_0\" :  \"" << WriteEnablePort_0.read() << "\" ";
        mAeslHdltvinHandle << "[WriteFullPort_0]" << endl;
        mAeslHdltvinHandle << WriteFullPort_0.read() << endl;
        mAeslHdltvinHandle << "[/WriteFullPort_0]" << endl;
        mHdltvinHandle << " , " <<  " \"WriteFullPort_0\" :  \"" << WriteFullPort_0.read() << "\" ";
        mAeslHdltvoutHandle << "[WriteDataPort_0]" << endl;
        mAeslHdltvoutHandle << WriteDataPort_0.read() << endl;
        mAeslHdltvoutHandle << "[/WriteDataPort_0]" << endl;
        mHdltvoutHandle << " , " <<  " \"WriteDataPort_0\" :  \"" << WriteDataPort_0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        mAeslHdltvinHandle << "[[/cycle]]" << endl;
        mAeslHdltvoutHandle << "[[/cycle]]" << endl;
        ap_cycleNo++;
    }
}

}

